spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

#    url: jdbc:mysql://172.31.150.67:3306/bdp?characterEncoding=utf-8&useSSL=false
    url: jdbc:log4jdbc:mysql://172.31.150.67:3306/bdp?characterEncoding=utf-8&useSSL=false&useUnicode=true&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
    hikari: # springboot 2.0 整合了hikari ,据说这是目前性能最好的java数据库连接池
      username: etl
      password: haizhi1234!
      minimum-idle: 5   # 最小空闲连接数量
      idle-timeout: 180000  # 空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 30  # 连接池最大连接数,默认是10
      auto-commit: true  # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      pool-name: MyHikariCP  # 连接池名称
      max-lifetime: 1800000  # 此属性控制池中连接的最长生命周期,值0表示无限生命周期,默认1800000即30分钟
      connection-timeout: 30000  # 数据库连接超时时间,默认30秒,即30000
#      connection-test-query: SELECT 1  # 连接池每分配一条连接前执行的查询语句（如：SELECT 1），以验证该连接是否是有效的。如果你的驱动程序支持 JDBC4,HikariCP 强烈建议我们不要设置此属性

#    username: root
#    password: 123456
#    url: jdbc:mysql://127.0.0.1:3306/dsp?characterEncoding=utf-8&useSSL=false
  jpa:
    hibernate:
      ddl-auto: update  # 第一次建表 create  后面用 update,要不然每次重启都会新建表
#    show-sql: true  # 打印执行的sql语句
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect  #设置数据库方言  记住必须要使用 MySQL5InnoDBDialect 指定数据库类型对应InnoDB  ;如果使用MySQLDialect 则对应的是MyISAM
#    properties:
#      hibernate:
#        format_sql: true  # 格式化打印的sql语句

  jackson:
    default-property-inclusion: non_null



test-key: JCccc-test-key-one



server:
  servlet:
    context-path: /dsp